{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openprime-app-backend.fullname" . }}
  labels:
    {{- include "openprime-app-backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openprime-app-backend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
  egress:
    {{- range .Values.networkPolicy.egress }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}