{{- if .Values.app.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openprime-app-backend.fullname" . }}-secrets
  labels:
    {{- include "openprime-app-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.app.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}